
package ch.psi.csm;

import ch.psi.camserver.ProxyClient;

/**
 *
 */
public class PanelServer extends javax.swing.JPanel {

    ProxyClient proxy;
    
    public PanelServer() {
        initComponents();
        setPipeline(false);
    }
    
    public void setUrl(String url){
        setProxy(new ProxyClient(url));
    }
    
    public String getUrl(){
       if (proxy==null){
           return null;
       }
       return proxy.getUrl();
    }   
    
    public void setProxy(ProxyClient proxy){
        this.proxy = proxy;
        panelStatus.setProxy(proxy);
        panelConfig.setProxy(proxy);
    }
    
    public ProxyClient getProxy(){
       return proxy;
    }      
    
    
   public boolean getPipeline(){
       return panelStatus.getPipeline();
   }

   public void setPipeline(boolean value){
       panelStatus.setPipeline(value);
       panelConfig.setPipeline(value);
   }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelStatus = new ch.psi.csm.PanelStatus();
        panelConfig = new ch.psi.csm.PanelConfig();

        jTabbedPane1.addTab("Status", panelStatus);
        jTabbedPane1.addTab("Config", panelConfig);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private ch.psi.csm.PanelConfig panelConfig;
    private ch.psi.csm.PanelStatus panelStatus;
    // End of variables declaration//GEN-END:variables
}
